kevinye:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost #选择数据库所在的IP地址（本机）
    port: 3306
    database: RETAIL #填写你需要的数据库
    username: root #用户名
    password: Ly@20060725 #密码

  redis:
    host: localhost #填写redis所在的IP地址
    port: 6379
    password: #redis的密码
    database:  0 #选择redis的那个database默认是0

  wechat:
    appid: wxb33402edb063d870
    secret: 265310cfa192a6d0ac16583834b2d039

  ai:
    appKey: hengnaovMBSHH1ziZBROc161ybO
    appSecret: coyvc4jh9h1kq1nr85rvbs09qfp7fale

  aliyun:
    oss:
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      accessKeyId: LTAI5tCtHFD1JTKSyozLoMRD
      accessKeySecret: 0auXq72gUuE5heCQICMFSChOaPDRH6
      bucketName: kevinye-web